# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40b7a5cd716cea6e530041a46a5268678b7c21f20768c7ae7ee4ece5a8fa24065232ece2b0552aa709cbf15bd62151ae3e9997994088001ee2b77c8336a81c67

test:
  secret_key_base: a742e02101509cec11c481bbeb2e8ce75f2a020a98cfc794f263d5cca398bfb24a348ade296356134ee3e7562150c155a37001e393c67d310795616b327e4179

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
